name: Verify
run-name: "Verify ${{ github.pull_request && format('PR {0}: {1}', github.event.pull_request.number, github.pull_request.title) || format('{0}: {1}', github.ref, github.event.head_commit.message) }}"
on:
  push:
  pull_request:
    branches: [main]
  workflow_call:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm i
      - run: pnpm test
      - run: pnpm typecheck
      - run: pnpm fmtcheck
      - run: echo 'Ba'
